[package]
name = "surviving"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
argh = "0.1.3"
sha3 = "0.9.1"
color-eyre = "0.5.1"
async-std = { version = "1.6.2", features = ["attributes"] }
